# Generated by Django 6.0.4 on 2026-05-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostapp', '0004_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='found_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lostapp.founditem'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='lost_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lostapp.lostitem'),
        ),
    ]
