# Generated by Django 6.0.4 on 2026-05-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostapp', '0006_claim_owner_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
