# Generated by Django 6.0.4 on 2026-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostapp', '0007_founditem_claimed_lostitem_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(default='Requested', max_length=20),
        ),
    ]
