# Generated by Django 6.0.4 on 2026-05-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostapp', '0008_alter_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
